import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, MapPin, PackageCheck, Sparkles } from "lucide-react";
import { categories, image, products } from "@/lib/store-data";
import { ProductGrid } from "@/components/product-card";

export default function HomePage() {
  return <>
    <section className="hero container"><div className="hero-copy"><div className="kicker"><span className="kicker-line" /> The destination for beauty that understands you</div><h1>Beauty,<br /><em>made brilliantly</em> personal.</h1><p>Discover hair, skin and beauty essentials selected for every texture, tone and routine — with expert care from Erith to your door.</p><div className="hero-actions"><Link className="button button-dark" href="/shop">Shop beauty <ArrowRight size={16} /></Link><Link className="text-button" href="/finders/hair">Find your hair <ArrowUpRight size={16} /></Link></div><div className="hero-proof"><span><Check size={14} /> Real store expertise</span><span><Check size={14} /> 7,000+ essentials</span><span><Check size={14} /> Same-day local delivery</span></div></div><div className="hero-visual"><div className="hero-image-main"><img src={image("photo-1522337360788-8b13dee7a37e", 1200)} alt="A beauty editorial portrait" /></div><div className="hero-caption"><span>01 / 04</span><span>Texture is always in.</span></div><div className="hero-stamp"><span>AGLORY</span><small>Beauty<br />in all<br />your forms</small></div><Link className="hero-product" href={`/products/${products[0].slug}`}><img src={products[0].image} alt={products[0].imageAlt} /><div><span className="eyebrow">Featured edit</span><strong>Complexion, considered.</strong></div><ArrowUpRight size={17} /></Link></div></section>
    <section className="trust-strip"><div className="container trust-grid"><div><PackageCheck size={21} /><span><strong>Same-day delivery</strong>On orders before 12pm</span></div><div><Sparkles size={21} /><span><strong>7,000+ products</strong>Expertly curated</span></div><div><Check size={21} /><span><strong>30-day returns</strong>Hassle-free shopping</span></div><div><Sparkles size={21} /><span><strong>Real beauty advice</strong>Call or WhatsApp the team</span></div></div></section>
    <section className="category-section container section-space"><div className="section-heading"><div><span className="eyebrow">Start with your ritual</span><h2>Shop by what<br /><em>moves you.</em></h2></div><Link className="text-button" href="/shop">View all categories <ArrowRight size={16} /></Link></div><div className="category-grid">{categories.map((category, index) => <Link className={`category-card category-${index}`} key={category.slug} href={`/category/${category.slug}`}><img src={category.image} alt="" /><span className="category-overlay" /><span className="category-content"><span>{String(index + 1).padStart(2, "0")}</span><strong>{category.name}</strong><small>{category.note}</small><ArrowUpRight size={17} /></span></Link>)}</div></section>
    <section className="product-section section-dark section-space"><div className="container"><div className="section-heading light"><div><span className="eyebrow">The considered edit</span><h2>Trending <em>now.</em></h2></div><Link className="text-button light-button" href="/shop">Shop all products <ArrowRight size={16} /></Link></div><ProductGrid items={products.slice(0, 4)} /></div></section>
    <section className="routine-banner container section-space"><div className="routine-image"><img src={image("photo-1608248543803-ba4f8c70ae0b", 1000)} alt="A nourishing hair care ritual" /></div><div className="routine-copy"><span className="eyebrow">A little help, beautifully given</span><h2>Build your<br /><em>best routine.</em></h2><p>Tell us what your beauty needs today. We’ll curate the next few steps — from wash day to glow day.</p><Link className="button button-dark" href="/finders/beauty">Start the finder <ArrowRight size={16} /></Link><div className="routine-goals"><span>Hair growth</span><span>Dryness</span><span>Protective styling</span><span>Uneven tone</span></div></div></section>
    <section className="blog-section section-space"><div className="container"><div className="section-heading"><div><span className="eyebrow">The Aglory Blog</span><h2>Beauty wisdom<br /><em>worth keeping.</em></h2></div><Link className="text-button" href="/blog">Read the latest edit <ArrowRight size={16} /></Link></div><p className="blog-intro">Practical, culturally-aware guidance for the routines you actually live — from choosing your undertone to caring for a wig between wears.</p><div className="blog-grid">{["protective-style-that-feels-like-you", "soft-skin-ritual-decoded", "finding-your-undertone"].map((slug, index) => { const post = ["How to choose a protective style that feels like you", "The soft-skin ritual, decoded", "Finding your undertone with confidence"][index]; return <Link className={`blog-card blog-card-${index}`} href={`/blog/${slug}`} key={slug}><img src={image(["photo-1522337360788-8b13dee7a37e", "photo-1570194065650-d99fb4ee38df", "photo-1596462502278-27bfdc403348"][index])} alt="" /><div className="blog-card-copy"><span className="eyebrow">{["Hair", "Skin", "Beauty"][index]} / {index + 4} min read</span><h3>{post}</h3><p>Thoughtful guidance for your next beauty ritual.</p><span className="blog-card-link">Read story <ArrowUpRight size={16} /></span></div></Link>; })}</div></div></section>
    <section className="store-section container section-space"><div className="store-photo"><img src={image("photo-1515377905703-c4788e51af15", 1100)} alt="Aglory Hair and Cosmetics store experience" /></div><div className="store-copy"><span className="eyebrow">Come say hello</span><h2>Your beauty place,<br /><em>in real life.</em></h2><p>Visit the Aglory Hair and Cosmetics team in Erith for expert advice, new arrivals and a little time to find what feels right.</p><div className="address"><MapPin size={17} /><span><strong>Aglory Hair and Cosmetics</strong>8 Cross Street, Erith<br />Kent DA8 1RB</span></div><div className="store-links"><Link className="button button-outline" href="/contact">Get directions <ArrowUpRight size={15} /></Link><a href="https://wa.me/4407446841404" target="_blank" rel="noreferrer" className="text-button">WhatsApp the team <ArrowRight size={15} /></a></div><span className="hours">Mon–Sat 9am–7pm · Sun 11am–4pm</span></div></section>
  </>;
}
