"use client";

import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Heart, MapPin, PackageCheck, Search, ShoppingBag, Sparkles } from "lucide-react";
import type { Product } from "@/lib/store-data";
import { brands, categories, blogPosts, image, money, products } from "@/lib/store-data";
import { ProductGrid } from "@/components/product-card";

export function RouteIntro({ eyebrow, title, body }: { eyebrow: string; title: React.ReactNode; body: string }) { return <div className="page-kicker"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{body}</p></div>; }

export function ShopCatalog({ items = products, title = <>Shop the <em>edit.</em></>, eyebrow = "Aglory catalogue" }: { items?: Product[]; title?: React.ReactNode; eyebrow?: string }) { return <section className="route-page container section-space"><RouteIntro eyebrow={eyebrow} title={title} body="7,000+ considered essentials for every texture, tone and ritual." /><div className="shop-toolbar"><div className="filter-pills">{["All products", "Hair care", "Wigs & extensions", "Skin & body", "Makeup", "Tools", "Men"].map((filter) => <Link href={filter === "All products" ? "/shop" : `/shop?category=${encodeURIComponent(filter)}`} key={filter}>{filter}</Link>)}</div><Link className="catalog-search" href="/search"><Search size={16} /><span>Search this edit</span></Link></div><div className="shop-meta"><span>{items.length * 24}+ results <span className="muted">· Curated for you</span></span><button>Featured <ChevronDown size={14} /></button></div><ProductGrid items={items} /><div className="shop-guide"><div><Sparkles size={18} /><span><strong>Need a little help?</strong> Find the right products for your hair, skin and beauty goals.</span></div><Link className="text-button" href="/finders/beauty">Take the finder <ArrowRight size={15} /></Link></div></section>; }

export function BrandsIndex() { return <section className="route-page brands-page container section-space"><RouteIntro eyebrow="The Aglory index" title={<>Brands with <em>intention.</em></>} body="Professional favourites, cult classics and the names worth knowing next." /><div className="featured-brand"><div><span className="eyebrow">Featured brand</span><h2>Made for your<br /><em>real routine.</em></h2><p>Explore thoughtful formulas from the brands our store team reaches for again and again.</p><Link className="button button-dark" href="/brands/shea-moisture">Shop Shea Moisture <ArrowRight size={16} /></Link></div><img src={image("photo-1556229010-6c3f2c9ca5f8", 1000)} alt="Shea Moisture body care" /></div><div className="brand-index"><div className="section-heading"><div><span className="eyebrow">Shop all brands</span><h2>A–Z, with <em>favorites.</em></h2></div><Link className="catalog-search" href="/search"><Search size={16} /><span>Find a brand</span></Link></div><div className="brand-list">{brands.map((brand, index) => <Link href={`/brands/${brand.toLowerCase().replaceAll(" ", "-")}`} key={brand}><span>{String(index + 1).padStart(2, "0")}</span><strong>{brand}</strong><ArrowUpRight size={16} /></Link>)}</div></div></section>; }

export function FinderPage({ kind }: { kind: "hair" | "beauty" }) { const hair = kind === "hair"; return <section className="finder-page container section-space"><div className="finder-intro"><span className="eyebrow">Your beauty, decoded</span><h1>{hair ? <>Find your<br /><em>hair.</em></> : <>Find what feels<br /><em>right for you.</em></>}</h1><p>A few thoughtful questions, then a considered edit picked from the Aglory catalogue.</p><div className="finder-progress"><span className="active" /><span /><span /></div></div><div className="finder-card"><span className="eyebrow">Step 1 of 3</span><h2>{hair ? "What kind of style are you looking for?" : "What does your routine need today?"}</h2><div className="finder-options">{(hair ? ["Wigs", "Braiding hair", "Crochet", "Weave", "Extensions"] : ["Hair growth", "Dry hair", "Protective styling", "Wig care", "Uneven tone", "Men’s grooming"]).map((option) => <Link href={`/finders/${kind}?step=2`} key={option}>{option}<ArrowRight size={16} /></Link>)}</div><Link className="button button-dark finder-next" href={`/finders/${kind}?step=2`}>Continue <ArrowRight size={16} /></Link></div></section>; }

export function BlogIndex() { return <section className="route-page container section-space"><RouteIntro eyebrow="The Aglory Blog" title={<>Beauty wisdom<br /><em>worth keeping.</em></>} body="Thoughtful, practical guidance for hair, skin, beauty and the rituals that make them yours." /><div className="blog-index-grid">{blogPosts.map((post) => <Link className="blog-card" href={`/blog/${post.slug}`} key={post.slug}><img src={post.image} alt="" /><div className="blog-card-copy"><span className="eyebrow">{post.category} / {post.read}</span><h3>{post.title}</h3><p>{post.excerpt}</p><span className="blog-card-link">Read story <ArrowUpRight size={16} /></span></div></Link>)}</div></section>; }

export function BlogArticle({ slug }: { slug: string }) { const post = blogPosts.find((item) => item.slug === slug) || blogPosts[0]; return <article className="article-page container section-space"><RouteIntro eyebrow={`${post.category} · ${post.read}`} title={<>{post.title}</>} body={post.excerpt} /><img className="article-hero" src={post.image} alt="" /><div className="article-body"><p>{post.excerpt} Beauty is personal, so the best routine is the one that makes sense for your texture, your time and your life.</p><h2>Start with what your routine needs.</h2><p>Look for products that help you feel confident in the next step. Keep the essentials close, learn what your hair and skin respond to, and let the ritual evolve with you.</p><blockquote>“The right beauty routine should feel like support, not another thing to keep up with.”</blockquote><h2>A few things to remember</h2><ul><li>Consistency matters more than complexity.</li><li>Choose products that suit your texture and lifestyle.</li><li>Ask for advice when you need it — Aglory is here to help.</li></ul><Link className="button button-dark" href="/shop">Shop the edit <ArrowRight size={16} /></Link></div></article>; }

export function AccountPage() { return <section className="account-page container section-space"><RouteIntro eyebrow="Welcome back" title={<>Your beauty <em>dashboard.</em></>} body="Keep your favorites close, track your orders and pick up where your routine left off." /><div className="account-grid"><div className="account-card account-welcome"><span className="account-avatar">A</span><span className="eyebrow">Your Aglory account</span><h2>Ready for your next<br /><em>good hair day?</em></h2><Link className="button button-dark" href="/shop">Buy again <ArrowRight size={16} /></Link></div><div className="account-card"><span className="eyebrow">Recent orders</span><h3>No orders yet</h3><p>Your next order will live here, along with delivery updates and easy reordering.</p><Link className="text-button" href="/shop">Start shopping <ArrowRight size={15} /></Link></div><div className="account-card"><span className="eyebrow">Saved edit</span><h3>Your wishlist is quiet.</h3><p>Keep the products you’re considering in one beautiful place.</p><Link className="text-button" href="/wishlist">Browse favorites <ArrowRight size={15} /></Link></div></div><div className="account-links"><Link href="/track-order"><PackageCheck size={18} /> Track an order <ArrowRight size={15} /></Link><Link href="/wishlist"><Heart size={18} /> Wishlist <ArrowRight size={15} /></Link><Link href="/contact"><Sparkles size={18} /> Need help? <ArrowRight size={15} /></Link></div></section>; }

export function ContactPage() { return <section className="contact-page container section-space"><div className="contact-intro"><span className="eyebrow">Come closer</span><h1>Let’s talk<br /><em>beauty.</em></h1><p>Questions about a product, your next style or a same-day delivery? The Aglory team is here.</p><div className="contact-details"><a href="tel:01322333305"><span>Call the store</span><strong>01322 333305</strong></a><a href="https://wa.me/4407446841404" target="_blank" rel="noreferrer"><span>WhatsApp us</span><strong>+44 07446 841404</strong></a><a href="mailto:info@agloryhairandcosmetics.co.uk"><span>Email</span><strong>info@agloryhairandcosmetics.co.uk</strong></a></div></div><div className="contact-form-card"><span className="eyebrow">Send a note</span><h2>What can we help<br /><em>you find?</em></h2><form onSubmit={(event) => event.preventDefault()}><input placeholder="Your name" aria-label="Your name" /><input type="email" placeholder="Email address" aria-label="Email address" /><select aria-label="What do you need help with?"><option>Product advice</option><option>Delivery & returns</option><option>Click & collect</option><option>Something else</option></select><textarea placeholder="Tell us a little more..." aria-label="Message" /><button className="button button-dark wide" type="submit">Send message <ArrowRight size={16} /></button></form></div></section>; }

export function UtilityPage({ title, eyebrow, body, children }: { title: React.ReactNode; eyebrow: string; body: string; children?: React.ReactNode }) { return <section className="utility-page container section-space"><RouteIntro eyebrow={eyebrow} title={title} body={body} />{children || <div className="utility-card"><Check size={25} /><h2>Ready when you are.</h2><p>This section is structured as a dedicated commerce route, ready for Shopify data and checkout integrations.</p><Link className="button button-dark" href="/shop">Continue shopping <ArrowRight size={16} /></Link></div>}</section>; }

export function CartSummary() { return <div className="utility-card cart-summary"><ShoppingBag size={28} /><h2>Your bag is waiting.</h2><p>Cart state is isolated in the storefront provider today and can be replaced by Shopify cart mutations later.</p><Link className="button button-dark" href="/shop">Shop the edit <ArrowRight size={16} /></Link></div>; }
